Remove plugin bluetoothsetup-gb7252 from gb7252 image
In the plugin is used the closed-source c library _gbbt, which is not compatible with python3, so the plugin does not work because it calls GSOD when strating:
ImportError: dynamic module does not define module export function (PyInit__gbbt)